name: OCI Terraform PoC

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      TF_VAR_tenancy_ocid: ${{ secrets.OCI_TENANCY_OCID }}
      TF_VAR_user_ocid: ${{ secrets.OCI_USER_OCID }}
      TF_VAR_fingerprint: ${{ secrets.OCI_FINGERPRINT }}
      TF_VAR_region: ${{ secrets.OCI_REGION }}
      TF_VAR_compartment_ocid: ${{ secrets.OCI_COMPARTMENT_OCID }}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      ###########################################################
      # Install OCI CLI
      ###########################################################
      - name: Install OCI CLI
        run: |
          bash -c "$(curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh)" -- --accept-all-defaults
          echo "$HOME/bin" >> $GITHUB_PATH

      ###########################################################
      # Create OCI Private Key
      ###########################################################
      - name: Create OCI API Key
        run: |
          mkdir -p ~/.oci

          cat <<EOF > ~/.oci/oci_api_key.pem
          ${{ secrets.OCI_PRIVATE_KEY }}
          EOF

          chmod 600 ~/.oci/oci_api_key.pem

      ###########################################################
      # Create OCI Config
      ###########################################################
      - name: Create OCI Config
        run: |
          cat <<EOF > ~/.oci/config
          [DEFAULT]
          user=${{ secrets.OCI_USER_OCID }}
          fingerprint=${{ secrets.OCI_FINGERPRINT }}
          tenancy=${{ secrets.OCI_TENANCY_OCID }}
          region=${{ secrets.OCI_REGION }}
          key_file=/home/runner/.oci/oci_api_key.pem
          EOF

      ###########################################################
      # Verify Config
      ###########################################################
      - name: Verify OCI Files
        run: |
          echo "========== CONFIG =========="
          cat ~/.oci/config

          echo ""
          echo "========== KEY =========="
          ls -l ~/.oci

      ###########################################################
      # Test OCI Authentication
      ###########################################################
      - name: Test OCI Login
        run: |
          oci os ns get

      ###########################################################
      # Terraform
      ###########################################################
      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve